using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EZGO.Api.Models.Enumerations
{
    /// <summary>
    /// TableNames, used for internal logging functionality (data auditing, certain tech messages). Do not use for anything else.
    /// NOTE! these will directly be converted to strings, therefor they will not be adhering to the naming convention.
    /// </summary>
    public enum TableNames
    {
        actions_action,
        actions_action_assigned_areas,
        actions_action_assigned_users,
        actions_actioncomment,
        actions_actioncommentviewed,
        actions_actionviewed,
        announcement,
        assessment_skillinstruction_items,
        assessment_skillinstructions,
        assessment_template_skillinstructions,
        assessment_templates,
        assessments,
        audits_audit,
        audits_audit_tasks,
        audits_audittemplate,
        audits_audittemplate_properties,
        audits_audittemplate_tasks,
        audits_properties,
        bookmarks,
        checklists_checklist,
        checklists_checklist_stage,
        checklists_checklist_stage_tasks,
        checklists_checklist_tasks,
        checklists_checklisttemplate,
        checklists_checklisttemplate_properties,
        checklists_checklisttemplate_stage,
        checklists_checklisttemplate_stage_tasks,
        checklists_checklisttemplate_tasks,
        checklists_properties,
        comments,
        comments_commentviewed,
        companies_area,
        companies_area_sap_pm_location_relations,
        companies_company,
        companies_generation_config,
        companies_shift,
        companies_properties,
        companies_setting,
        factoryfeed_messages,
        factoryfeeds,
        holding,
        holding_company,
        holding_setting,
        holdingunit,
        holdingunit_company,
        matrices,
        matrix_user_groups,
        matrix_user_skills,
        picture_proof,
        profiles_user,
        profiles_user_allowed_areas,
        profiles_user_areas,
        profiles_user_groups,
        profiles_user_extended_details,
        properties,
        propertygroups,
        propertyvalue,
        propertyvaluekind,
        resource_languages,
        resource_settings,
        sap_pm_notification,
        shared_template,
        tags_tag,
        tags_tag_company,
        tags_tag_configuration,
        tags_tag_relation,
        tags_taggroup,
        tags_taggroup_tags,
        tasks_properties,
        tasks_task,
        tasks_task_audit_link,
        tasks_task_checklist_link,
        tasks_taskrecurrency,
        tasks_taskrecurrency_one_time_shifts,
        tasks_taskrecurrency_shifts,
        tasks_tasktemplate,
        tasks_tasktemplate_properties,
        tasks_tasktemplate_tags_links,
        tasks_tasktemplatestep,
        tasks_tasktemplatetag,
        uploads_requesteds3link,
        user_group_users,
        user_groups,
        user_skills,
        user_skill_uservalues,
        version_app,
        workinstruction_template_audittemplate,
        workinstruction_template_audittemplate_item,
        workinstruction_template_checklisttemplate,
        workinstruction_template_checklisttemplate_item,
        workinstruction_template_items,
        workinstruction_template_tasktemplate,
        workinstruction_templates,
        workinstruction_templates_viewed
    }

    public enum TableFields
    {
        action_id,
        area_id,
        assessment_id,
        assessment_template_id,
        audit_id,
        audittemplate_id,
        checklist_id,
        checklist_stage_id,
        checklisttemplate_id,
        checklisttemplate_stage_id,
        comment_id,
        company_id,
        holding_id,
        tag_id,
        task_id,
        tasktemplate_id,
        taskrecurrency_id,
        user_id,
        workinstruction_template_id
    }

}
