using System.Collections.Generic;

namespace WebApp.Logic
{
    public class Country
    {
        public string Name { get; set; }
        public string Iso2 { get; set; }
        public string Iso3 { get; set; }
    }

    public static class CountryList
    {
        public static List<Country> GetCountries()
        {
            return new List<Country>
            {
                new Country { Name = "Afghanistan", Iso2 = "AF", Iso3 = "AFG" },
                new Country { Name = "Albania", Iso2 = "AL", Iso3 = "ALB" },
                new Country { Name = "Algeria", Iso2 = "DZ", Iso3 = "DZA" },
                new Country { Name = "Andorra", Iso2 = "AD", Iso3 = "AND" },
                new Country { Name = "Angola", Iso2 = "AO", Iso3 = "AGO" },
                new Country { Name = "Argentina", Iso2 = "AR", Iso3 = "ARG" },
                new Country { Name = "Armenia", Iso2 = "AM", Iso3 = "ARM" },
                new Country { Name = "Australia", Iso2 = "AU", Iso3 = "AUS" },
                new Country { Name = "Austria", Iso2 = "AT", Iso3 = "AUT" },
                new Country { Name = "Azerbaijan", Iso2 = "AZ", Iso3 = "AZE" },
                new Country { Name = "Bahamas", Iso2 = "BS", Iso3 = "BHS" },
                new Country { Name = "Bahrain", Iso2 = "BH", Iso3 = "BHR" },
                new Country { Name = "Bangladesh", Iso2 = "BD", Iso3 = "BGD" },
                new Country { Name = "Barbados", Iso2 = "BB", Iso3 = "BRB" },
                new Country { Name = "Belarus", Iso2 = "BY", Iso3 = "BLR" },
                new Country { Name = "Belgium", Iso2 = "BE", Iso3 = "BEL" },
                new Country { Name = "Belize", Iso2 = "BZ", Iso3 = "BLZ" },
                new Country { Name = "Benin", Iso2 = "BJ", Iso3 = "BEN" },
                new Country { Name = "Bhutan", Iso2 = "BT", Iso3 = "BTN" },
                new Country { Name = "Bolivia", Iso2 = "BO", Iso3 = "BOL" },
                new Country { Name = "Bosnia and Herzegovina", Iso2 = "BA", Iso3 = "BIH" },
                new Country { Name = "Botswana", Iso2 = "BW", Iso3 = "BWA" },
                new Country { Name = "Brazil", Iso2 = "BR", Iso3 = "BRA" },
                new Country { Name = "Brunei", Iso2 = "BN", Iso3 = "BRN" },
                new Country { Name = "Bulgaria", Iso2 = "BG", Iso3 = "BGR" },
                new Country { Name = "Burkina Faso", Iso2 = "BF", Iso3 = "BFA" },
                new Country { Name = "Burundi", Iso2 = "BI", Iso3 = "BDI" },
                new Country { Name = "Cambodia", Iso2 = "KH", Iso3 = "KHM" },
                new Country { Name = "Cameroon", Iso2 = "CM", Iso3 = "CMR" },
                new Country { Name = "Canada", Iso2 = "CA", Iso3 = "CAN" },
                new Country { Name = "Cape Verde", Iso2 = "CV", Iso3 = "CPV" },
                new Country { Name = "Central African Republic", Iso2 = "CF", Iso3 = "CAF" },
                new Country { Name = "Chad", Iso2 = "TD", Iso3 = "TCD" },
                new Country { Name = "Chile", Iso2 = "CL", Iso3 = "CHL" },
                new Country { Name = "China", Iso2 = "CN", Iso3 = "CHN" },
                new Country { Name = "Colombia", Iso2 = "CO", Iso3 = "COL" },
                new Country { Name = "Comoros", Iso2 = "KM", Iso3 = "COM" },
                new Country { Name = "Congo (Brazzaville)", Iso2 = "CG", Iso3 = "COG" },
                new Country { Name = "Congo (Kinshasa)", Iso2 = "CD", Iso3 = "COD" },
                new Country { Name = "Costa Rica", Iso2 = "CR", Iso3 = "CRI" },
                new Country { Name = "Croatia", Iso2 = "HR", Iso3 = "HRV" },
                new Country { Name = "Cuba", Iso2 = "CU", Iso3 = "CUB" },
                new Country { Name = "Cyprus", Iso2 = "CY", Iso3 = "CYP" },
                new Country { Name = "Czech Republic", Iso2 = "CZ", Iso3 = "CZE" },
                new Country { Name = "Denmark", Iso2 = "DK", Iso3 = "DNK" },
                new Country { Name = "Djibouti", Iso2 = "DJ", Iso3 = "DJI" },
                new Country { Name = "Dominica", Iso2 = "DM", Iso3 = "DMA" },
                new Country { Name = "Dominican Republic", Iso2 = "DO", Iso3 = "DOM" },
                new Country { Name = "Ecuador", Iso2 = "EC", Iso3 = "ECU" },
                new Country { Name = "Egypt", Iso2 = "EG", Iso3 = "EGY" },
                new Country { Name = "El Salvador", Iso2 = "SV", Iso3 = "SLV" },
                new Country { Name = "Equatorial Guinea", Iso2 = "GQ", Iso3 = "GNQ" },
                new Country { Name = "Eritrea", Iso2 = "ER", Iso3 = "ERI" },
                new Country { Name = "Estonia", Iso2 = "EE", Iso3 = "EST" },
                new Country { Name = "Eswatini", Iso2 = "SZ", Iso3 = "SWZ" },
                new Country { Name = "Ethiopia", Iso2 = "ET", Iso3 = "ETH" },
                new Country { Name = "Fiji", Iso2 = "FJ", Iso3 = "FJI" },
                new Country { Name = "Finland", Iso2 = "FI", Iso3 = "FIN" },
                new Country { Name = "France", Iso2 = "FR", Iso3 = "FRA" },
                new Country { Name = "Gabon", Iso2 = "GA", Iso3 = "GAB" },
                new Country { Name = "Gambia", Iso2 = "GM", Iso3 = "GMB" },
                new Country { Name = "Georgia", Iso2 = "GE", Iso3 = "GEO" },
                new Country { Name = "Germany", Iso2 = "DE", Iso3 = "DEU" },
                new Country { Name = "Ghana", Iso2 = "GH", Iso3 = "GHA" },
                new Country { Name = "Greece", Iso2 = "GR", Iso3 = "GRC" },
                new Country { Name = "Greenland", Iso2 = "GL", Iso3 = "GRL" },
                new Country { Name = "Grenada", Iso2 = "GD", Iso3 = "GRD" },
                new Country { Name = "Guatemala", Iso2 = "GT", Iso3 = "GTM" },
                new Country { Name = "Guinea", Iso2 = "GN", Iso3 = "GIN" },
                new Country { Name = "Guinea-Bissau", Iso2 = "GW", Iso3 = "GNB" },
                new Country { Name = "Guyana", Iso2 = "GY", Iso3 = "GUY" },
                new Country { Name = "Haiti", Iso2 = "HT", Iso3 = "HTI" },
                new Country { Name = "Honduras", Iso2 = "HN", Iso3 = "HND" },
                new Country { Name = "Hungary", Iso2 = "HU", Iso3 = "HUN" },
                new Country { Name = "Iceland", Iso2 = "IS", Iso3 = "ISL" },
                new Country { Name = "India", Iso2 = "IN", Iso3 = "IND" },
                new Country { Name = "Indonesia", Iso2 = "ID", Iso3 = "IDN" },
                new Country { Name = "Iran", Iso2 = "IR", Iso3 = "IRN" },
                new Country { Name = "Iraq", Iso2 = "IQ", Iso3 = "IRQ" },
                new Country { Name = "Ireland", Iso2 = "IE", Iso3 = "IRL" },
                new Country { Name = "Israel", Iso2 = "IL", Iso3 = "ISR" },
                new Country { Name = "Italy", Iso2 = "IT", Iso3 = "ITA" },
                new Country { Name = "Jamaica", Iso2 = "JM", Iso3 = "JAM" },
                new Country { Name = "Japan", Iso2 = "JP", Iso3 = "JPN" },
                new Country { Name = "Jordan", Iso2 = "JO", Iso3 = "JOR" },
                new Country { Name = "Kazakhstan", Iso2 = "KZ", Iso3 = "KAZ" },
                new Country { Name = "Kenya", Iso2 = "KE", Iso3 = "KEN" },
                new Country { Name = "Kiribati", Iso2 = "KI", Iso3 = "KIR" },
                new Country { Name = "Kuwait", Iso2 = "KW", Iso3 = "KWT" },
                new Country { Name = "Kyrgyzstan", Iso2 = "KG", Iso3 = "KGZ" },
                new Country { Name = "Laos", Iso2 = "LA", Iso3 = "LAO" },
                new Country { Name = "Latvia", Iso2 = "LV", Iso3 = "LVA" },
                new Country { Name = "Lebanon", Iso2 = "LB", Iso3 = "LBN" },
                new Country { Name = "Lesotho", Iso2 = "LS", Iso3 = "LSO" },
                new Country { Name = "Liberia", Iso2 = "LR", Iso3 = "LBR" },
                new Country { Name = "Libya", Iso2 = "LY", Iso3 = "LBY" },
                new Country { Name = "Liechtenstein", Iso2 = "LI", Iso3 = "LIE" },
                new Country { Name = "Lithuania", Iso2 = "LT", Iso3 = "LTU" },
                new Country { Name = "Luxembourg", Iso2 = "LU", Iso3 = "LUX" },
                new Country { Name = "Madagascar", Iso2 = "MG", Iso3 = "MDG" },
                new Country { Name = "Malawi", Iso2 = "MW", Iso3 = "MWI" },
                new Country { Name = "Malaysia", Iso2 = "MY", Iso3 = "MYS" },
                new Country { Name = "Maldives", Iso2 = "MV", Iso3 = "MDV" },
                new Country { Name = "Mali", Iso2 = "ML", Iso3 = "MLI" },
                new Country { Name = "Malta", Iso2 = "MT", Iso3 = "MLT" },
                new Country { Name = "Marshall Islands", Iso2 = "MH", Iso3 = "MHL" },
                new Country { Name = "Mauritania", Iso2 = "MR", Iso3 = "MRT" },
                new Country { Name = "Mauritius", Iso2 = "MU", Iso3 = "MUS" },
                new Country { Name = "Mexico", Iso2 = "MX", Iso3 = "MEX" },
                new Country { Name = "Micronesia", Iso2 = "FM", Iso3 = "FSM" },
                new Country { Name = "Moldova", Iso2 = "MD", Iso3 = "MDA" },
                new Country { Name = "Monaco", Iso2 = "MC", Iso3 = "MCO" },
                new Country { Name = "Mongolia", Iso2 = "MN", Iso3 = "MNG" },
                new Country { Name = "Montenegro", Iso2 = "ME", Iso3 = "MNE" },
                new Country { Name = "Morocco", Iso2 = "MA", Iso3 = "MAR" },
                new Country { Name = "Mozambique", Iso2 = "MZ", Iso3 = "MOZ" },
                new Country { Name = "Myanmar", Iso2 = "MM", Iso3 = "MMR" },
                new Country { Name = "Namibia", Iso2 = "NA", Iso3 = "NAM" },
                new Country { Name = "Nauru", Iso2 = "NR", Iso3 = "NRU" },
                new Country { Name = "Nepal", Iso2 = "NP", Iso3 = "NPL" },
                new Country { Name = "Netherlands", Iso2 = "NL", Iso3 = "NLD" },
                new Country { Name = "New Zealand", Iso2 = "NZ", Iso3 = "NZL" },
                new Country { Name = "Nicaragua", Iso2 = "NI", Iso3 = "NIC" },
                new Country { Name = "Niger", Iso2 = "NE", Iso3 = "NER" },
                new Country { Name = "Nigeria", Iso2 = "NG", Iso3 = "NGA" },
                new Country { Name = "North Korea", Iso2 = "KP", Iso3 = "PRK" },
                new Country { Name = "North Macedonia", Iso2 = "MK", Iso3 = "MKD" },
                new Country { Name = "Norway", Iso2 = "NO", Iso3 = "NOR" },
                new Country { Name = "Oman", Iso2 = "OM", Iso3 = "OMN" },
                new Country { Name = "Pakistan", Iso2 = "PK", Iso3 = "PAK" },
                new Country { Name = "Palau", Iso2 = "PW", Iso3 = "PLW" },
                new Country { Name = "Palestine", Iso2 = "PS", Iso3 = "PSE" },
                new Country { Name = "Panama", Iso2 = "PA", Iso3 = "PAN" },
                new Country { Name = "Papua New Guinea", Iso2 = "PG", Iso3 = "PNG" },
                new Country { Name = "Paraguay", Iso2 = "PY", Iso3 = "PRY" },
                new Country { Name = "Peru", Iso2 = "PE", Iso3 = "PER" },
                new Country { Name = "Philippines", Iso2 = "PH", Iso3 = "PHL" },
                new Country { Name = "Poland", Iso2 = "PL", Iso3 = "POL" },
                new Country { Name = "Portugal", Iso2 = "PT", Iso3 = "PRT" },
                new Country { Name = "Qatar", Iso2 = "QA", Iso3 = "QAT" },
                new Country { Name = "Romania", Iso2 = "RO", Iso3 = "ROU" },
                new Country { Name = "Russia", Iso2 = "RU", Iso3 = "RUS" },
                new Country { Name = "Rwanda", Iso2 = "RW", Iso3 = "RWA" },
                new Country { Name = "Saint Kitts and Nevis", Iso2 = "KN", Iso3 = "KNA" },
                new Country { Name = "Saint Lucia", Iso2 = "LC", Iso3 = "LCA" },
                new Country { Name = "Saint Vincent", Iso2 = "VC", Iso3 = "VCT" },
                new Country { Name = "Samoa", Iso2 = "WS", Iso3 = "WSM" },
                new Country { Name = "San Marino", Iso2 = "SM", Iso3 = "SMR" },
                new Country { Name = "Sao Tome and Principe", Iso2 = "ST", Iso3 = "STP" },
                new Country { Name = "Saudi Arabia", Iso2 = "SA", Iso3 = "SAU" },
                new Country { Name = "Senegal", Iso2 = "SN", Iso3 = "SEN" },
                new Country { Name = "Serbia", Iso2 = "RS", Iso3 = "SRB" },
                new Country { Name = "Seychelles", Iso2 = "SC", Iso3 = "SYC" },
                new Country { Name = "Sierra Leone", Iso2 = "SL", Iso3 = "SLE" },
                new Country { Name = "Singapore", Iso2 = "SG", Iso3 = "SGP" },
                new Country { Name = "Slovakia", Iso2 = "SK", Iso3 = "SVK" },
                new Country { Name = "Slovenia", Iso2 = "SI", Iso3 = "SVN" },
                new Country { Name = "Solomon Islands", Iso2 = "SB", Iso3 = "SLB" },
                new Country { Name = "Somalia", Iso2 = "SO", Iso3 = "SOM" },
                new Country { Name = "South Africa", Iso2 = "ZA", Iso3 = "ZAF" },
                new Country { Name = "South Korea", Iso2 = "KR", Iso3 = "KOR" },
                new Country { Name = "South Sudan", Iso2 = "SS", Iso3 = "SSD" },
                new Country { Name = "Spain", Iso2 = "ES", Iso3 = "ESP" },
                new Country { Name = "Sri Lanka", Iso2 = "LK", Iso3 = "LKA" },
                new Country { Name = "Sudan", Iso2 = "SD", Iso3 = "SDN" },
                new Country { Name = "Suriname", Iso2 = "SR", Iso3 = "SUR" },
                new Country { Name = "Sweden", Iso2 = "SE", Iso3 = "SWE" },
                new Country { Name = "Switzerland", Iso2 = "CH", Iso3 = "CHE" },
                new Country { Name = "Syria", Iso2 = "SY", Iso3 = "SYR" },
                new Country { Name = "Taiwan", Iso2 = "TW", Iso3 = "TWN" },
                new Country { Name = "Tajikistan", Iso2 = "TJ", Iso3 = "TJK" },
                new Country { Name = "Tanzania", Iso2 = "TZ", Iso3 = "TZA" },
                new Country { Name = "Thailand", Iso2 = "TH", Iso3 = "THA" },
                new Country { Name = "Timor-Leste", Iso2 = "TL", Iso3 = "TLS" },
                new Country { Name = "Togo", Iso2 = "TG", Iso3 = "TGO" },
                new Country { Name = "Tonga", Iso2 = "TO", Iso3 = "TON" },
                new Country { Name = "Trinidad and Tobago", Iso2 = "TT", Iso3 = "TTO" },
                new Country { Name = "Tunisia", Iso2 = "TN", Iso3 = "TUN" },
                new Country { Name = "Turkey", Iso2 = "TR", Iso3 = "TUR" },
                new Country { Name = "Turkmenistan", Iso2 = "TM", Iso3 = "TKM" },
                new Country { Name = "Tuvalu", Iso2 = "TV", Iso3 = "TUV" },
                new Country { Name = "Uganda", Iso2 = "UG", Iso3 = "UGA" },
                new Country { Name = "Ukraine", Iso2 = "UA", Iso3 = "UKR" },
                new Country { Name = "United Arab Emirates", Iso2 = "AE", Iso3 = "ARE" },
                new Country { Name = "United Kingdom", Iso2 = "GB", Iso3 = "GBR" },
                new Country { Name = "United States", Iso2 = "US", Iso3 = "USA" },
                new Country { Name = "Uruguay", Iso2 = "UY", Iso3 = "URY" },
                new Country { Name = "Uzbekistan", Iso2 = "UZ", Iso3 = "UZB" },
                new Country { Name = "Vanuatu", Iso2 = "VU", Iso3 = "VUT" },
                new Country { Name = "Vatican City", Iso2 = "VA", Iso3 = "VAT" },
                new Country { Name = "Venezuela", Iso2 = "VE", Iso3 = "VEN" },
                new Country { Name = "Vietnam", Iso2 = "VN", Iso3 = "VNM" },
                new Country { Name = "Yemen", Iso2 = "YE", Iso3 = "YEM" },
                new Country { Name = "Zambia", Iso2 = "ZM", Iso3 = "ZMB" },
                new Country { Name = "Zimbabwe", Iso2 = "ZW", Iso3 = "ZWE" },
            };
        }
    }
}
