#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZGO.Maui.Core.PdfTemplates
{
using System;
using System.Collections.Generic;

#line 5 "CompletedAssessmentTemplate.cshtml"
using System.Linq;

#line default
#line hidden
using System.Text;

#line 1 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.Models;

#line default
#line hidden

#line 2 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.Models.Assessments;

#line default
#line hidden

#line 3 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.Converter;

#line default
#line hidden

#line 4 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.Classes;

#line default
#line hidden

#line 6 "CompletedAssessmentTemplate.cshtml"
using EZGO.Api.Models.Basic;

#line default
#line hidden

#line 7 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.Models.Tasks;

#line default
#line hidden

#line 8 "CompletedAssessmentTemplate.cshtml"
using EZGO.Api.Models.Enumerations;

#line default
#line hidden

#line 9 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.Extensions;

#line default
#line hidden

#line 10 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.Models.Actions;

#line default
#line hidden

#line 11 "CompletedAssessmentTemplate.cshtml"
using EZGO.Api.Models;

#line default
#line hidden

#line 12 "CompletedAssessmentTemplate.cshtml"
using EZGO.Maui.Core.PdfTemplates;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class CompletedAssessmentTemplate : CompletedAssessmentTemplateBase
{

#line hidden

#line 13 "CompletedAssessmentTemplate.cshtml"
public AssessmentsModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 15 "CompletedAssessmentTemplate.cshtml"
  
    var RedColor = ResourceHelper.GetApplicationResource<Color>("RedColor").ToHtmlString();
    var GreenColor = ResourceHelper.GetApplicationResource<Color>("GreenColor").ToHtmlString();
    var SkippedColor = ResourceHelper.GetApplicationResource<Color>("SkippedColor").ToHtmlString();
    var dir = Settings.IsRightToLeftLanguage ? "rtl" : "ltr";
    var scoreColorCalculator = new InstructionScoreToColorConverter();

    void GetIconAndColor(BasicAssessmentInstructionItemModel instruction, out string icon, out string color)
    {
        icon = instruction.Score.ToString();

        switch (instruction.Score)
        {
            case 5:
                color = GreenColor;
                break;
            case 4:
                color = GreenColor;
                break;
            case 3:
                color = SkippedColor;
                break;
            case 2:
                color = SkippedColor;
                break;
            case 1:
                color = RedColor;
                break;
            case 0:
                color = RedColor;
                break;
            default:
                color = SkippedColor;
                break;
        }
    }

    string GetTagBackgroundColor(string colorCode)
    {
        var color = "#D3D3D3";
        if (!colorCode.IsNullOrEmpty())
        {
            if (colorCode.StartsWith("#"))
                color = colorCode;
            else
                color = "#" + colorCode;
        }
        return color;
    }

    string GetIconClass(string iconStyle)
    {
        if (iconStyle == "solid")
            return "iconSolid";

        return "iconRegular";
    }


#line default
#line hidden
WriteLiteral("\n\n<!DOCTYPE html>\n<html");

WriteLiteral(" lang=\"en\"");

WriteAttribute ("dir", " dir=\"", "\""

#line 75 "CompletedAssessmentTemplate.cshtml"
, Tuple.Create<string,object,bool> ("", dir

#line default
#line hidden
, false)
);
WriteLiteral(">\n<head>\n    <meta");

WriteLiteral(" charset=\"UTF-8\"");

WriteLiteral(" />\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"print\"");

WriteLiteral(">\n        ");

WriteLiteral(@"@page {
            size: auto; /* auto is the initial value */
            margin: 0mm; /* this affects the margin in the printer settings */
        }

        * {
            -webkit-print-color-adjust: exact !important; /* needed for fixing issues with colors on ios */
        }

        html {
            background-color: #FFFFFF;
            margin: 0px; /* this affects the margin on the html before sending to printer */
        }

        body {
            margin: 0mm; /* margin you want for the content */
        }
    </style>
    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\n        ");

WriteLiteral(@"@font-face {
            font-family: 'Material Icons';
            font-style: normal;
            font-weight: 400;
            src: url('MaterialIcons-Regular.ttf');
        }

        .material-icons {
            font-family: 'Material Icons';
            font-weight: normal;
            font-style: normal;
            font-size: 24px;
            line-height: 1;
            letter-spacing: normal;
            text-transform: none;
            display: inline-block;
            white-space: nowrap;
            word-wrap: normal;
            direction: ltr;
            -webkit-font-feature-settings: 'liga';
            -webkit-font-smoothing: antialiased;
            color: white;
        }

        ");

WriteLiteral("@font-face {\n            font-family: Roboto-Regular;\n            src: url(\"Robot" +
"o-Regular.ttf\");\n        }\n\n        ");

WriteLiteral("@font-face {\n            font-family: Roboto-Regular;\n            src: url(\"Robot" +
"o-Bold.ttf\");\n            font-weight: bold;\n        }\n\n        ");

WriteLiteral("@font-face {\n            font-family: Font-Awesome-Regular;\n            font-styl" +
"e: normal;\n            font-weight: 400;\n            src: url(\'fa_pro_regular_40" +
"0.otf\');\n        }\n\n        ");

WriteLiteral("@font-face {\n            font-family: Font-Awesome-Solid;\n            font-style:" +
" normal;\n            font-weight: 900;\n            src: url(\'fa_pro_solid_900.ot" +
"f\');\n        }\n\n        .tagIcon {\n            font-style: normal;\n            o" +
"verflow: hidden;\n            white-space: nowrap;\n            width: 35px;\n     " +
"       padding: 3px 6px;\n        }\n\n        .iconSolid {\n            font-family" +
": Font-Awesome-Solid;\n        }\n\n        .iconRegular {\n            font-family:" +
" Font-Awesome-Regular;\n        }\n\n        .tagsList {\n            display: flex;" +
"\n            flex-wrap: wrap;\n        }\n\n        .tagItem {\n            margin-r" +
"ight: 10px;\n            margin-bottom: 10px;\n            height: 20px;\n         " +
"   width: 115px;\n            display: flex;\n            align-items: center;\n   " +
"         color: white;\n        }\n\n        html, body {\n            font-family: " +
"Roboto-Regular;\n            margin: 0px;\n            padding: 0px;\n            h" +
"eight: auto;\n            width: 100%;\n        }\n\n            body > *:not(table)" +
" {\n                margin-left: 40px;\n                margin-right: 40px;\n      " +
"      }\n\n        .no-padding {\n            padding: 0px !important;\n        }\n\n " +
"       body {\n            width: 100%;\n        }\n\n        table {\n            bo" +
"rder-spacing: 0;\n            table-layout: auto;\n        }\n\n        .id {\n      " +
"      padding-left: 0 10px 0 10px;\n        }\n\n        .status-icon-box {\n       " +
"     border-radius: 50%;\n            width: 30px;\n            height: 30px;\n    " +
"        display: flex;\n            align-items: center;\n            justify-cont" +
"ent: center;\n            color: #fff;\n        }\n\n        .camera-icon-box-small " +
"{\n            border-radius: 50%;\n            width: 10px;\n            height: 1" +
"0px;\n            display: flex;\n            align-items: center;\n            jus" +
"tify-content: center;\n            color: #fff;\n            position: relative;\n " +
"           left: 20px;\n            top: 5px;\n            border: 1px solid;\n    " +
"        border-color: white;\n        }\n\n        .ok {\n            background-col" +
"or: #1ed760;\n        }\n\n        .not-ok {\n            background-color: red;\n   " +
"     }\n\n        .skip {\n            background-color: #EB7D16;\n        }\n\n      " +
"  .break-before {\n            page-break-before: always;\n        }\n\n        .bre" +
"ak-after {\n            page-break-after: always;\n        }\n\n        td {\n       " +
"     font-size: 12px;\n            padding: 0px 5px;\n        }\n\n        hr {\n    " +
"        height: 2px;\n            background-color: #ccc;\n            border: 0px" +
";\n        }\n\n        tr {\n            padding-right: 5px;\n        }\n\n        th " +
"span {\n            font-size: 10px;\n        }\n\n        .page-title {\n           " +
" color: #A9A9A9;\n            font-size: 10px;\n        }\n\n        .stripe {\n     " +
"       background-color: #eee;\n        }\n\n        #signatures div:not(:first-chi" +
"ld) {\n            margin-left: 50px;\n        }\n\n        .action-pictures-box img" +
" {\n            margin-right: .5em;\n        }\n\n        .action-pictures-box {\n   " +
"         display: flex;\n            flex-flow: row wrap;\n            justify-ite" +
"ms: flex-start;\n            align-items: center;\n            background: #eee;\n " +
"           height: 120px;\n        }\n\n        .grid-container {\n            displ" +
"ay: flex;\n        }\n\n        .grid-item {\n            padding-left: 10px;\n      " +
"  }\n\n        img {\n            object-fit: cover;\n        }\n\n        .value-item" +
" {\n            padding-left: 10px;\n        }\n\n        .value-style {\n           " +
" display: flex;\n            align-items: center;\n            word-wrap: break-wo" +
"rd;\n            background: white;\n            height: 30px;\n        }\n\n        " +
".bold {\n            font-weight: bold;\n        }\n\n        span.text {\n          " +
"  font-size: 8px;\n            padding-right: 10px;\n        }\n\n        .wrap-cont" +
"ent {\n            word-break: break-all;\n            width: 100%;\n        }\n    " +
"</style>\n</head>\n<body>\n    <div>\n        <h2");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(">");


#line 339 "CompletedAssessmentTemplate.cshtml"
                            Write(Model.Name);


#line default
#line hidden
WriteLiteral("</h2>\n        <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral("><strong>");


#line 340 "CompletedAssessmentTemplate.cshtml"
                                    Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_DATE_AND_TIME"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 340 "CompletedAssessmentTemplate.cshtml"
                                                                                                                         Write(Model.LocalCompletedAt.ToString(PdfConstants.GetDateTimeFormat(), null));


#line default
#line hidden
WriteLiteral("</p>\n\n");


#line 342 "CompletedAssessmentTemplate.cshtml"
        

#line default
#line hidden

#line 342 "CompletedAssessmentTemplate.cshtml"
         if (Model.Tags != null && Model.Tags.Any())
        {


#line default
#line hidden
WriteLiteral("            <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(">\n                <strong>");


#line 345 "CompletedAssessmentTemplate.cshtml"
                    Write(TranslateExtension.GetValueFromDictionary("BASE_TEXT_TAGS"));


#line default
#line hidden
WriteLiteral(":</strong>\n                <tr>\n                    <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral("></td>\n                    <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"tagsList\"");

WriteLiteral(">\n");


#line 350 "CompletedAssessmentTemplate.cshtml"
                            

#line default
#line hidden

#line 350 "CompletedAssessmentTemplate.cshtml"
                             foreach (var tag in Model.Tags)
                            {
                                var backgroundColor = GetTagBackgroundColor(tag.ColorCode);


#line default
#line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"tagItem\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 353 "CompletedAssessmentTemplate.cshtml"
                                      , Tuple.Create<string,object,bool> (" ", backgroundColor

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n");


#line 354 "CompletedAssessmentTemplate.cshtml"
                                    

#line default
#line hidden

#line 354 "CompletedAssessmentTemplate.cshtml"
                                     if (!tag.IconName.IsNullOrEmpty())
                                    {


#line default
#line hidden
WriteLiteral("                                        <i");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "tagIcon", true)

#line 356 "CompletedAssessmentTemplate.cshtml"
                  , Tuple.Create<string,object,bool> (" ", GetIconClass(tag.IconStyle)

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 356 "CompletedAssessmentTemplate.cshtml"
                                                                                   Write(tag.IconName);


#line default
#line hidden
WriteLiteral("</i>\n");


#line 357 "CompletedAssessmentTemplate.cshtml"
                                    }


#line default
#line hidden
WriteLiteral("                                    <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");


#line 358 "CompletedAssessmentTemplate.cshtml"
                                                  Write(tag.Name);


#line default
#line hidden
WriteLiteral("</span>\n                                </div>\n");


#line 360 "CompletedAssessmentTemplate.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                        </div>\n                    </td>\n                </tr>\n  " +
"          </p>\n");


#line 365 "CompletedAssessmentTemplate.cshtml"
        }


#line default
#line hidden
WriteLiteral("    </div>\n\n");


#line 368 "CompletedAssessmentTemplate.cshtml"
    

#line default
#line hidden

#line 368 "CompletedAssessmentTemplate.cshtml"
       var i = 0; 

#line default
#line hidden
WriteLiteral("\n");


#line 369 "CompletedAssessmentTemplate.cshtml"
    

#line default
#line hidden

#line 369 "CompletedAssessmentTemplate.cshtml"
     foreach (var skillInstructions in Model.SkillInstructions)
    {


#line default
#line hidden
WriteLiteral("        <div>\n            <h3>");


#line 372 "CompletedAssessmentTemplate.cshtml"
           Write(skillInstructions.Name);


#line default
#line hidden
WriteLiteral("</h3>\n");


#line 373 "CompletedAssessmentTemplate.cshtml"
            

#line default
#line hidden

#line 373 "CompletedAssessmentTemplate.cshtml"
             if (skillInstructions.Tags != null && skillInstructions.Tags.Any())
            {


#line default
#line hidden
WriteLiteral("                <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(">\n                    <h4>");


#line 376 "CompletedAssessmentTemplate.cshtml"
                    Write(TranslateExtension.GetValueFromDictionary("BASE_TEXT_TAGS"));


#line default
#line hidden
WriteLiteral(":</h4>\n                    <div");

WriteLiteral(" class=\"tagsList\"");

WriteLiteral(">\n");


#line 378 "CompletedAssessmentTemplate.cshtml"
                        

#line default
#line hidden

#line 378 "CompletedAssessmentTemplate.cshtml"
                         foreach (var tag in skillInstructions.Tags)
                        {
                            var backgroundColor = GetTagBackgroundColor(tag.ColorCode);


#line default
#line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"tagItem\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 381 "CompletedAssessmentTemplate.cshtml"
                                  , Tuple.Create<string,object,bool> (" ", backgroundColor

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n");


#line 382 "CompletedAssessmentTemplate.cshtml"
                                

#line default
#line hidden

#line 382 "CompletedAssessmentTemplate.cshtml"
                                 if (!tag.IconName.IsNullOrEmpty())
                                {


#line default
#line hidden
WriteLiteral("                                    <i");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "tagIcon", true)

#line 384 "CompletedAssessmentTemplate.cshtml"
              , Tuple.Create<string,object,bool> (" ", GetIconClass(tag.IconStyle)

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 384 "CompletedAssessmentTemplate.cshtml"
                                                                               Write(tag.IconName);


#line default
#line hidden
WriteLiteral("</i>\n");


#line 385 "CompletedAssessmentTemplate.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");


#line 386 "CompletedAssessmentTemplate.cshtml"
                                              Write(tag.Name);


#line default
#line hidden
WriteLiteral("</span>\n                            </div>\n");


#line 388 "CompletedAssessmentTemplate.cshtml"
                        }


#line default
#line hidden
WriteLiteral("                    </div>\n                </p>\n");


#line 391 "CompletedAssessmentTemplate.cshtml"
            }


#line default
#line hidden
WriteLiteral("\n            <table");

WriteLiteral(" style=\"width: 100%; padding-top: 10px;\"");

WriteLiteral(" class=\"striped\"");

WriteLiteral(">\n                <thead>\n                    <tr>\n                        <th>&n" +
"bsp;</th>\n                        <th");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:#A9A9A9;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: 400;\"");

WriteLiteral(">");


#line 397 "CompletedAssessmentTemplate.cshtml"
                                                                                                               Write(TranslateExtension.GetValueFromDictionary("INSTRUCTIONS_SCREEN_TITLE"));


#line default
#line hidden
WriteLiteral("</span></span></th>\n                        <th>&nbsp;</th>\n                     " +
"   <th");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:#A9A9A9;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: 400;\"");

WriteLiteral(">");


#line 399 "CompletedAssessmentTemplate.cshtml"
                                                                                                               Write(TranslateExtension.GetValueFromDictionary("AUDIT_SCORE_TEXT").Replace(":", ""));


#line default
#line hidden
WriteLiteral("</span></span></th>\n                    </tr>\n                    <tr");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                        <th");

WriteLiteral(" colspan=\"9\"");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                            <hr />\n                        </th>\n              " +
"      </tr>\n                </thead>\n                <tbody>\n");


#line 408 "CompletedAssessmentTemplate.cshtml"
                    

#line default
#line hidden

#line 408 "CompletedAssessmentTemplate.cshtml"
                       var k = 0; 

#line default
#line hidden
WriteLiteral("\n");


#line 409 "CompletedAssessmentTemplate.cshtml"
                    

#line default
#line hidden

#line 409 "CompletedAssessmentTemplate.cshtml"
                     foreach (var item in skillInstructions.InstructionItems)
                    {


#line default
#line hidden
WriteLiteral("                        <tr");

WriteAttribute ("class", " class=\"", "\""

#line 411 "CompletedAssessmentTemplate.cshtml"
, Tuple.Create<string,object,bool> ("", k % 2 == 0 ? "stripe" : ""

#line default
#line hidden
, false)
);
WriteLiteral(">\n                            <td");

WriteLiteral(" class=\"id\"");

WriteLiteral(" style=\"text-align: center; height:80px; width: 40px; font-size:12px\"");

WriteLiteral(">");


#line 412 "CompletedAssessmentTemplate.cshtml"
                                                                                                            Write(k + 1);


#line default
#line hidden
WriteLiteral("</td>\n");


#line 413 "CompletedAssessmentTemplate.cshtml"
                            

#line default
#line hidden

#line 413 "CompletedAssessmentTemplate.cshtml"
                              
                                var imageUrl = @ImageHelpers.GetFullImageUrlFromName(item.Picture);
                                GetIconAndColor(item, out var icon, out var colorHex);
                            

#line default
#line hidden
WriteLiteral("\n                            <td");

WriteLiteral(" style=\"vertical-align: central;\"");

WriteLiteral("><img");

WriteLiteral(" alt=\"placeholder\"");

WriteAttribute ("src", " src=\"", "\""

#line 417 "CompletedAssessmentTemplate.cshtml"
                                                      , Tuple.Create<string,object,bool> ("", imageUrl

#line default
#line hidden
, false)
);
WriteLiteral(" style=\"height: 60px; width: 60px; vertical-align: central;\"");

WriteLiteral(" /></td>\n                            <td");

WriteLiteral(" style=\"font-size: 12px; text-align:left; justify-content:start; width:80%;\"");

WriteLiteral(">\n                                <p");

WriteLiteral(" style=\"margin: 5px\"");

WriteLiteral(">");


#line 419 "CompletedAssessmentTemplate.cshtml"
                                                  Write(item.Name);


#line default
#line hidden
WriteLiteral("</p>\n                            </td>\n                            <td");

WriteLiteral(" style=\"vertical-align: central;\"");

WriteLiteral(">\n                                <div");

WriteLiteral(" class=\"status-icon-box\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 422 "CompletedAssessmentTemplate.cshtml"
                                              , Tuple.Create<string,object,bool> (" ", colorHex

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n                                    <span");

WriteLiteral(" style=\"text-align: center; font-size: 15px;\"");

WriteLiteral(">");


#line 423 "CompletedAssessmentTemplate.cshtml"
                                                                                  Write(icon);


#line default
#line hidden
WriteLiteral("</span>\n                                </div>\n                            </td>\n" +
"                        </tr>\n");


#line 427 "CompletedAssessmentTemplate.cshtml"
                        k++;
                    }


#line default
#line hidden
WriteLiteral("                </tbody>\n            </table>\n            <p");

WriteLiteral(" style=\"text-align: right; font-size: 12px; padding-right: 10px;\"");

WriteLiteral(">");


#line 431 "CompletedAssessmentTemplate.cshtml"
                                                                            Write(TranslateExtension.GetValueFromDictionary("AVARAGE_SCORE"));


#line default
#line hidden
WriteLiteral(" ");


#line 431 "CompletedAssessmentTemplate.cshtml"
                                                                                                                                          Write(skillInstructions.AverageScoreString);


#line default
#line hidden
WriteLiteral("%</p><br><br>\n        </div>\n");


#line 433 "CompletedAssessmentTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("    <hr />\n    <div>\n        <p");

WriteLiteral(" style=\"text-align: right; font-size: 12px; padding-right: 10px;\"");

WriteLiteral(">");


#line 436 "CompletedAssessmentTemplate.cshtml"
                                                                        Write(TranslateExtension.GetValueFromDictionary("AVARAGE_SCORE"));


#line default
#line hidden
WriteLiteral(" ");


#line 436 "CompletedAssessmentTemplate.cshtml"
                                                                                                                                      Write(Model.AverageScoreString);


#line default
#line hidden
WriteLiteral("%</p><br><br>\n    </div>\n    <table");

WriteLiteral(" style=\"width: 100%; padding:20px; page-break-inside: avoid\"");

WriteLiteral(">\n        <tbody>\n");


#line 440 "CompletedAssessmentTemplate.cshtml"
            

#line default
#line hidden

#line 440 "CompletedAssessmentTemplate.cshtml"
             if (Model.Signatures?.Count > 0)
            {


#line default
#line hidden
WriteLiteral("                <tr>\n                    <td>&nbsp;</td>\n");


#line 444 "CompletedAssessmentTemplate.cshtml"
                    

#line default
#line hidden

#line 444 "CompletedAssessmentTemplate.cshtml"
                     foreach (var signature in (Model.Signatures ?? new List<SignatureModel>()))
                    {


#line default
#line hidden
WriteLiteral("                        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\n");

WriteLiteral("                            ");


#line 447 "CompletedAssessmentTemplate.cshtml"
                       Write(signature.SignedBy);


#line default
#line hidden
WriteLiteral("\n                        </td>\n");


#line 449 "CompletedAssessmentTemplate.cshtml"
                    }


#line default
#line hidden
WriteLiteral("\n                </tr>\n");

WriteLiteral("                <tr>\n                    <td><span");

WriteLiteral(" style=\"color:#A9A9A9;\"");

WriteLiteral(">EZ-GO Assessment Report</span></td>\n");


#line 454 "CompletedAssessmentTemplate.cshtml"
                    

#line default
#line hidden

#line 454 "CompletedAssessmentTemplate.cshtml"
                     foreach (var signature in (Model.Signatures ?? new List<SignatureModel>()))
                    {
                        if (!string.IsNullOrEmpty(signature.SignatureImage))
                        {
                            var signatureUrl = @ImageHelpers.GetFullImageUrlFromName(signature.SignatureImage);

                            

#line default
#line hidden
WriteLiteral("<td><img");

WriteLiteral(" alt=\"afbeelding\"");

WriteAttribute ("src", " src=\"", "\""

#line 460 "CompletedAssessmentTemplate.cshtml"
                    , Tuple.Create<string,object,bool> ("", signatureUrl

#line default
#line hidden
, false)
);
WriteLiteral(" height=\"100\"");

WriteLiteral(" style=\"display:block; margin: auto\"");

WriteLiteral(" /></td>\n");


#line 461 "CompletedAssessmentTemplate.cshtml"
                        }
                    }


#line default
#line hidden
WriteLiteral("                </tr>\n");


#line 464 "CompletedAssessmentTemplate.cshtml"
            }
            else
            {


#line default
#line hidden
WriteLiteral("                <tr>\n                    <td");

WriteLiteral(" style=\"font-size: 12px; text-align:left; justify-content:start\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"bold\"");

WriteLiteral(">");


#line 469 "CompletedAssessmentTemplate.cshtml"
                                       Write(TranslateExtension.GetValueFromDictionary("ASSESSEE"));


#line default
#line hidden
WriteLiteral(":</span> ");


#line 469 "CompletedAssessmentTemplate.cshtml"
                                                                                                        Write(Model.CompletedFor);


#line default
#line hidden
WriteLiteral("\n                    </td>\n                </tr>\n");

WriteLiteral("                <tr>\n                    <td");

WriteLiteral(" style=\"font-size: 12px; text-align:left; justify-content:start\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"bold\"");

WriteLiteral(">");


#line 474 "CompletedAssessmentTemplate.cshtml"
                                       Write(TranslateExtension.GetValueFromDictionary("ASSESSOR"));


#line default
#line hidden
WriteLiteral(":</span> ");


#line 474 "CompletedAssessmentTemplate.cshtml"
                                                                                                        Write(Model.Assessor);


#line default
#line hidden
WriteLiteral("\n                    </td>\n                </tr>\n");


#line 477 "CompletedAssessmentTemplate.cshtml"
            }


#line default
#line hidden
WriteLiteral("\n        </tbody>\n    </table>\n</body>\n</html>\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class CompletedAssessmentTemplateBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
