#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZGO.Maui.Core.PdfTemplates
{
using System;
using System.Collections.Generic;

#line 4 "CompletedAuditTemplate.cshtml"
using System.Linq;

#line default
#line hidden
using System.Text;

#line 1 "CompletedAuditTemplate.cshtml"
using EZGO.Maui.Core.Classes;

#line default
#line hidden

#line 2 "CompletedAuditTemplate.cshtml"
using EZGO.Maui.Core.Models;

#line default
#line hidden

#line 3 "CompletedAuditTemplate.cshtml"
using EZGO.Maui.Core.Models.Audits;

#line default
#line hidden

#line 5 "CompletedAuditTemplate.cshtml"
using EZGO.Api.Models.Basic;

#line default
#line hidden

#line 6 "CompletedAuditTemplate.cshtml"
using EZGO.Maui.Core.Models.Tasks;

#line default
#line hidden

#line 7 "CompletedAuditTemplate.cshtml"
using EZGO.Api.Models.Enumerations;

#line default
#line hidden

#line 8 "CompletedAuditTemplate.cshtml"
using EZGO.Maui.Core.Extensions;

#line default
#line hidden

#line 9 "CompletedAuditTemplate.cshtml"
using EZGO.Maui.Core.Models.Actions;

#line default
#line hidden

#line 10 "CompletedAuditTemplate.cshtml"
using EZGO.Api.Models;

#line default
#line hidden

#line 11 "CompletedAuditTemplate.cshtml"
using EZGO.Maui.Core.PdfTemplates;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class CompletedAuditTemplate : CompletedAuditTemplateBase
{

#line hidden

#line 12 "CompletedAuditTemplate.cshtml"
public AuditsModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 13 "CompletedAuditTemplate.cshtml"
  
    var hasScore = (ScoreTypeEnum)Enum.Parse(typeof(ScoreTypeEnum), Model.ScoreType ?? "thumbs", true) == ScoreTypeEnum.Score;
    var calculator = Model.ScoreColorCalculator;
    var RedColor = ResourceHelper.GetApplicationResource<Color>("RedColor").ToHtmlString();
    var GreenColor = ResourceHelper.GetApplicationResource<Color>("GreenColor").ToHtmlString();
    var SkippedColor = ResourceHelper.GetApplicationResource<Color>("SkippedColor").ToHtmlString();
    var dir = Settings.IsRightToLeftLanguage ? "rtl" : "ltr";

    void GetIconAndColor(TasksTaskModel task, out string icon, out string color)
    {
        switch (task.Status.ToLower())
        {
            case "ok":
                icon = hasScore ? task.Score.ToString() : "thumb_up";
                color = GreenColor;
                break;

            case "skipped":
                icon = "fast_forward";
                color = SkippedColor;
                break;
            default:
                icon = hasScore ? task.Score.ToString() : "thumb_down";
                color = RedColor;
                break;
        }
        if (hasScore && task.Status != "skipped")
        {
            color = calculator.GetColor(task.Score ?? 0).ToHtmlString();
        }
    }

    string GetTagBackgroundColor(string colorCode)
    {
        var color = "#D3D3D3";
        if (!colorCode.IsNullOrEmpty())
        {
            if (colorCode.StartsWith("#"))
                color = colorCode;
            else
                color = "#" + colorCode;
        }
        return color;
    }

    string GetIconClass(string iconStyle)
    {
        if (iconStyle == "solid")
            return "iconSolid";

        return "iconRegular";
    }


#line default
#line hidden
WriteLiteral("\n<!DOCTYPE html>\n<html");

WriteLiteral(" lang=\"en\"");

WriteAttribute ("dir", " dir=\"", "\""

#line 67 "CompletedAuditTemplate.cshtml"
, Tuple.Create<string,object,bool> ("", dir

#line default
#line hidden
, false)
);
WriteLiteral(">\n<head>\n    <meta");

WriteLiteral(" charset=\"UTF-8\"");

WriteLiteral(" />\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"print\"");

WriteLiteral(">\n        ");

WriteLiteral(@"@page {
            size: auto; /* auto is the initial value */
            margin: 0mm; /* this affects the margin in the printer settings */
        }

        * {
            -webkit-print-color-adjust: exact !important; /* needed for fixing issues with colors on ios */
        }

        html {
            background-color: #FFFFFF;
            margin: 0px; /* this affects the margin on the html before sending to printer */
        }

        body {
            margin: 0mm; /* margin you want for the content */
        }
    </style>
    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\n        ");

WriteLiteral(@"@font-face {
            font-family: 'Material Icons';
            font-style: normal;
            font-weight: 400;
            src: url('MaterialIcons-Regular.ttf');
        }

        .material-icons {
            font-family: 'Material Icons';
            font-weight: normal;
            font-style: normal;
            font-size: 24px;
            line-height: 1;
            letter-spacing: normal;
            text-transform: none;
            display: inline-block;
            white-space: nowrap;
            word-wrap: normal;
            direction: ltr;
            -webkit-font-feature-settings: 'liga';
            -webkit-font-smoothing: antialiased;
            color: white;
        }

        ");

WriteLiteral("@font-face {\n            font-family: Roboto-Regular;\n            src: url(\"Robot" +
"o-Regular.ttf\");\n        }\n\n        ");

WriteLiteral("@font-face {\n            font-family: Roboto-Regular;\n            src: url(\"Robot" +
"o-Bold.ttf\");\n            font-weight: bold;\n        }\n\n        ");

WriteLiteral("@font-face {\n            font-family: Font-Awesome-Regular;\n            font-styl" +
"e: normal;\n            font-weight: 400;\n            src: url(\'fa_pro_regular_40" +
"0.otf\');\n        }\n\n        ");

WriteLiteral("@font-face {\n            font-family: Font-Awesome-Solid;\n            font-style:" +
" normal;\n            font-weight: 900;\n            src: url(\'fa_pro_solid_900.ot" +
"f\');\n        }\n\n        .tagIcon {\n            font-style: normal;\n            o" +
"verflow: hidden;\n            white-space: nowrap;\n            width: 35px;\n     " +
"       padding: 3px 6px;\n        }\n\n        .iconSolid {\n            font-family" +
": Font-Awesome-Solid;\n        }\n\n        .iconRegular {\n            font-family:" +
" Font-Awesome-Regular;\n        }\n\n        html, body {\n            font-family: " +
"Roboto-Regular;\n            margin: 0px;\n            padding: 0px;\n            h" +
"eight: auto;\n            width: 100%;\n        }\n\n            body > *:not(table)" +
" {\n                margin-left: 40px;\n                margin-right: 40px;\n      " +
"      }\n\n        .no-padding {\n            padding: 0px !important;\n        }\n\n " +
"       body {\n            width: 100%;\n        }\n\n        table {\n            bo" +
"rder-spacing: 0;\n            table-layout: auto;\n        }\n\n        .id {\n      " +
"      padding-left: 0 10px 0 10px;\n        }\n\n        .status-icon-box {\n       " +
"     border-radius: 50%;\n            width: 30px;\n            height: 30px;\n    " +
"        display: flex;\n            align-items: center;\n            justify-cont" +
"ent: center;\n            color: #fff;\n        }\n\n        .camera-icon-box-small " +
"{\n            border-radius: 50%;\n            width: 10px;\n            height: 1" +
"0px;\n            display: flex;\n            align-items: center;\n            jus" +
"tify-content: center;\n            color: #fff;\n            position: relative;\n " +
"           left: 20px;\n            top: 5px;\n            border: 1px solid;\n    " +
"        border-color: white;\n        }\n\n        .ok {\n            background-col" +
"or: #1ed760;\n        }\n\n        .not-ok {\n            background-color: red;\n   " +
"     }\n\n        .skip {\n            background-color: #EB7D16;\n        }\n\n      " +
"  .break-before {\n            page-break-before: always;\n        }\n\n        .bre" +
"ak-after {\n            page-break-after: always;\n        }\n\n        td {\n       " +
"     font-size: 12px;\n            padding: 0px 5px;\n        }\n\n        hr {\n    " +
"        height: 2px;\n            background-color: #ccc;\n            border: 0px" +
";\n        }\n\n        tr {\n            padding-right: 5px;\n        }\n\n        th " +
"span {\n            font-size: 10px;\n        }\n\n        .page-title {\n           " +
" color: #A9A9A9;\n            font-size: 10px;\n        }\n\n        .stripe {\n     " +
"       background-color: #eee;\n        }\n\n        #signatures div:not(:first-chi" +
"ld) {\n            margin-left: 50px;\n        }\n\n        .action-pictures-box img" +
" {\n            margin-right: .5em;\n        }\n\n        .action-pictures-box {\n   " +
"         display: flex;\n            flex-flow: row wrap;\n            justify-ite" +
"ms: flex-start;\n            align-items: center;\n            background: #eee;\n " +
"           height: 120px;\n        }\n\n        .grid-container {\n            displ" +
"ay: flex;\n        }\n\n        .grid-item {\n            padding-left: 10px;\n      " +
"  }\n\n        img {\n            object-fit: cover;\n        }\n\n        .value-item" +
" {\n            padding-left: 10px;\n        }\n\n        .value-style {\n           " +
" display: flex;\n            align-items: center;\n            word-wrap: break-wo" +
"rd;\n            background: white;\n            height: 30px;\n        }\n\n        " +
".bold {\n            font-weight: bold;\n        }\n\n        .wrap-content {\n      " +
"      word-break: break-all;\n            width: 100%;\n        }\n\n        .tagsLi" +
"st {\n            display: flex;\n            flex-wrap: wrap;\n        }\n\n        " +
".tagItem {\n            margin-right: 10px;\n            margin-bottom: 10px;\n    " +
"        height: 20px;\n            width: 115px;\n            display: flex;\n     " +
"       align-items: center;\n            color: white;\n        }\n\n        span.te" +
"xt {\n            font-size: 8px;\n            padding-right: 10px;\n        }\n\n   " +
"     img.icon {\n            width: 15px;\n            height: 15px;\n            p" +
"adding-right: 5px;\n        }\n    </style>\n</head>\n<body>\n    <div>\n        <h2");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(">");


#line 337 "CompletedAuditTemplate.cshtml"
                            Write(Model.Name);


#line default
#line hidden
WriteLiteral("</h2>\n\n        <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral("><strong>");


#line 339 "CompletedAuditTemplate.cshtml"
                                    Write(TranslateExtension.GetValueFromDictionary("SIDEBAR_TITLE_AUDIT"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 339 "CompletedAuditTemplate.cshtml"
                                                                                                                 Write(Model.Name);


#line default
#line hidden
WriteLiteral("</p>\n\n        <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral("><strong>");


#line 341 "CompletedAuditTemplate.cshtml"
                                    Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_DATE_AND_TIME"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 341 "CompletedAuditTemplate.cshtml"
                                                                                                                         Write(Model.LocalSignedAt.ToString(PdfConstants.GetDateTimeFormat(), null));


#line default
#line hidden
WriteLiteral("</p>\n\n");


#line 343 "CompletedAuditTemplate.cshtml"
        

#line default
#line hidden

#line 343 "CompletedAuditTemplate.cshtml"
         if (Model.Tags != null && Model.Tags.Any())
        {


#line default
#line hidden
WriteLiteral("            <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(">\n                <strong>");


#line 346 "CompletedAuditTemplate.cshtml"
                    Write(TranslateExtension.GetValueFromDictionary("BASE_TEXT_TAGS"));


#line default
#line hidden
WriteLiteral(":</strong>\n                <tr>\n                    <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral("></td>\n                    <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"tagsList\"");

WriteLiteral(">\n");


#line 351 "CompletedAuditTemplate.cshtml"
                            

#line default
#line hidden

#line 351 "CompletedAuditTemplate.cshtml"
                             foreach (var tag in Model.Tags)
                            {
                                var backgroundColor = GetTagBackgroundColor(tag.ColorCode);


#line default
#line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"tagItem\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 354 "CompletedAuditTemplate.cshtml"
                                      , Tuple.Create<string,object,bool> (" ", backgroundColor

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n");


#line 355 "CompletedAuditTemplate.cshtml"
                                    

#line default
#line hidden

#line 355 "CompletedAuditTemplate.cshtml"
                                     if (!tag.IconName.IsNullOrEmpty())
                                    {


#line default
#line hidden
WriteLiteral("                                        <i");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "tagIcon", true)

#line 357 "CompletedAuditTemplate.cshtml"
                  , Tuple.Create<string,object,bool> (" ", GetIconClass(tag.IconStyle)

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 357 "CompletedAuditTemplate.cshtml"
                                                                                   Write(tag.IconName);


#line default
#line hidden
WriteLiteral("</i>\n");


#line 358 "CompletedAuditTemplate.cshtml"
                                    }


#line default
#line hidden
WriteLiteral("                                    <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");


#line 359 "CompletedAuditTemplate.cshtml"
                                                  Write(tag.Name);


#line default
#line hidden
WriteLiteral("</span>\n                                </div>\n");


#line 361 "CompletedAuditTemplate.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                        </div>\n                    </td>\n                </tr>\n  " +
"          </p>\n");


#line 366 "CompletedAuditTemplate.cshtml"
        }


#line default
#line hidden
WriteLiteral("    </div>\n\n");


#line 369 "CompletedAuditTemplate.cshtml"
    

#line default
#line hidden

#line 369 "CompletedAuditTemplate.cshtml"
     if (Model.OpenFieldsProperties != null && Model.OpenFieldsProperties.Count() > 0)
    {


#line default
#line hidden
WriteLiteral("        <hr />\n");


#line 372 "CompletedAuditTemplate.cshtml"



#line default
#line hidden
WriteLiteral("        <div>\n");


#line 374 "CompletedAuditTemplate.cshtml"
            

#line default
#line hidden

#line 374 "CompletedAuditTemplate.cshtml"
             for (int openFieldIndex = 0; openFieldIndex < Model.OpenFieldsPropertyUserValues.Count(); openFieldIndex++)
            {
                var property = Model.OpenFieldsProperties[openFieldIndex];
                var title = property.TitleDisplay;
                var isRequired = property.IsRequired;

                var fieldValue = Model.OpenFieldsPropertyUserValues[openFieldIndex].GetFieldValue();
                fieldValue ??= string.Empty;



#line default
#line hidden
WriteLiteral("                <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(">\n                    <strong>\n");


#line 385 "CompletedAuditTemplate.cshtml"
                        

#line default
#line hidden

#line 385 "CompletedAuditTemplate.cshtml"
                         if (isRequired)
                        {


#line default
#line hidden
WriteLiteral("                            <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">*</span>\n");


#line 388 "CompletedAuditTemplate.cshtml"
                        }


#line default
#line hidden
WriteLiteral("                        ");


#line 389 "CompletedAuditTemplate.cshtml"
                   Write(title);


#line default
#line hidden
WriteLiteral(" :\n                    </strong>\n");

WriteLiteral("                    ");


#line 391 "CompletedAuditTemplate.cshtml"
               Write(fieldValue);


#line default
#line hidden
WriteLiteral("\n                </p>\n");


#line 393 "CompletedAuditTemplate.cshtml"
            }


#line default
#line hidden
WriteLiteral("        </div>\n");


#line 395 "CompletedAuditTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("\n    <table");

WriteLiteral(" style=\"width: 100%; padding-top: 10px;\"");

WriteLiteral(" class=\"striped\"");

WriteLiteral(">\n        <thead>\n            <tr>\n                <th>&nbsp;</th>\n              " +
"  <th");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:#A9A9A9;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: 400;\"");

WriteLiteral(">");


#line 401 "CompletedAuditTemplate.cshtml"
                                                                                                       Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_TABLE_CHECKS_COLLUMN_NAME"));


#line default
#line hidden
WriteLiteral("</span></span></th>\n                <th>&nbsp;</th>\n                <th");

WriteLiteral(" style=\"text-align: left; padding-left: 5px; padding-right: 5px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:#A9A9A9;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: 400;\"");

WriteLiteral(">");


#line 403 "CompletedAuditTemplate.cshtml"
                                                                                                                                              Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_REMARK"));


#line default
#line hidden
WriteLiteral("</span></span></th>\n                <th");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:#A9A9A9;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: 400;\"");

WriteLiteral(">");


#line 404 "CompletedAuditTemplate.cshtml"
                                                                                                       Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_STATUS"));


#line default
#line hidden
WriteLiteral("</span></span></th>\n            </tr>\n            <tr");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                <th");

WriteLiteral(" colspan=\"9\"");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                    <hr />\n                </th>\n            </tr>\n        </th" +
"ead>\n        <tbody>\n");


#line 413 "CompletedAuditTemplate.cshtml"
            

#line default
#line hidden

#line 413 "CompletedAuditTemplate.cshtml"
               var i = 0; 

#line default
#line hidden
WriteLiteral("\n");


#line 414 "CompletedAuditTemplate.cshtml"
            

#line default
#line hidden

#line 414 "CompletedAuditTemplate.cshtml"
             foreach (var task in Model.Tasks)
            {


#line default
#line hidden
WriteLiteral("                <tr>\n                <tr");

WriteAttribute ("class", " class=\"", "\""

#line 417 "CompletedAuditTemplate.cshtml"
, Tuple.Create<string,object,bool> ("", i % 2 == 0 ? "stripe" : ""

#line default
#line hidden
, false)
);
WriteLiteral(">\n                    <td");

WriteLiteral(" class=\"id\"");

WriteLiteral(" style=\"text-align: center; height:80px; width: 40px; font-size:12px\"");

WriteLiteral(">");


#line 418 "CompletedAuditTemplate.cshtml"
                                                                                                    Write(i + 1);


#line default
#line hidden
WriteLiteral("</td>\n");


#line 419 "CompletedAuditTemplate.cshtml"
                    

#line default
#line hidden

#line 419 "CompletedAuditTemplate.cshtml"
                      
                        var imageUrl = @ImageHelpers.GetFullImageUrlFromName(task.Picture);
                        GetIconAndColor(task, out var icon, out var colorHex);
                    

#line default
#line hidden
WriteLiteral("\n                    <td");

WriteLiteral(" style=\"vertical-align: central;\"");

WriteLiteral("><img");

WriteLiteral(" alt=\"placeholder\"");

WriteAttribute ("src", " src=\"", "\""

#line 423 "CompletedAuditTemplate.cshtml"
                                              , Tuple.Create<string,object,bool> ("", imageUrl

#line default
#line hidden
, false)
);
WriteLiteral(" style=\"height: 60px; width: 60px; vertical-align: central;\"");

WriteLiteral(" /></td>\n                    <td");

WriteLiteral(" style=\"font-size: 12px; text-align:left; justify-content:start\"");

WriteLiteral(">\n                        <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(" style=\"margin: 5px\"");

WriteLiteral(">");


#line 425 "CompletedAuditTemplate.cshtml"
                                                               Write(task.Name);


#line default
#line hidden
WriteLiteral("</p>\n                        <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral(" style=\"margin: 5px\"");

WriteLiteral(">");


#line 426 "CompletedAuditTemplate.cshtml"
                                                               Write(task.PropertyValuesString);


#line default
#line hidden
WriteLiteral("</p>\n                    </td>\n                    <td>\n");


#line 429 "CompletedAuditTemplate.cshtml"
                        

#line default
#line hidden

#line 429 "CompletedAuditTemplate.cshtml"
                         if (task.HasCommentsOrActions)
                        {


#line default
#line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"status-icon-box skip\"");

WriteLiteral(">\n                                <i");

WriteLiteral(" class=\"material-icons\"");

WriteLiteral(" style=\"text-align: center; font-size: 15px;\"");

WriteLiteral(">flash_on</i>\n                            </div>\n");


#line 434 "CompletedAuditTemplate.cshtml"
                        }


#line default
#line hidden
WriteLiteral("                    </td>\n                    <td");

WriteLiteral(" style=\"vertical-align: central;\"");

WriteLiteral(">\n                        <div>\n");


#line 438 "CompletedAuditTemplate.cshtml"
                            

#line default
#line hidden

#line 438 "CompletedAuditTemplate.cshtml"
                             if (task.HasPictureProof)
                            {


#line default
#line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"camera-icon-box-small\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 440 "CompletedAuditTemplate.cshtml"
                                                    , Tuple.Create<string,object,bool> (" ", colorHex

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n                                    <i");

WriteLiteral(" class=\"material-icons\"");

WriteLiteral(" style=\"text-align: center; font-size: 8px;\"");

WriteLiteral(">photo_camera</i>\n                                </div>\n");


#line 443 "CompletedAuditTemplate.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"status-icon-box\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 444 "CompletedAuditTemplate.cshtml"
                                          , Tuple.Create<string,object,bool> (" ", colorHex

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n");


#line 445 "CompletedAuditTemplate.cshtml"
                                

#line default
#line hidden

#line 445 "CompletedAuditTemplate.cshtml"
                                 if (hasScore && task.Status != "skipped")
                                {


#line default
#line hidden
WriteLiteral("                                    <span");

WriteLiteral(" style=\"text-align: center; font-size: 15px;\"");

WriteLiteral(">");


#line 447 "CompletedAuditTemplate.cshtml"
                                                                                  Write(icon);


#line default
#line hidden
WriteLiteral("</span>\n");


#line 448 "CompletedAuditTemplate.cshtml"
                                }
                                else
                                {


#line default
#line hidden
WriteLiteral("                                    <i");

WriteLiteral(" class=\"material-icons\"");

WriteLiteral(" style=\"text-align: center; font-size: 15px;\"");

WriteLiteral(">");


#line 451 "CompletedAuditTemplate.cshtml"
                                                                                                      Write(icon);


#line default
#line hidden
WriteLiteral("</i>\n");


#line 452 "CompletedAuditTemplate.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </div>\n                        </div>\n               " +
"     </td>\n                </tr>\n");


#line 457 "CompletedAuditTemplate.cshtml"
                

#line default
#line hidden

#line 457 "CompletedAuditTemplate.cshtml"
                 if (task.Tags != null && task.Tags.Any())
                {


#line default
#line hidden
WriteLiteral("                    <tr");

WriteAttribute ("class", " class=\"", "\""

#line 459 "CompletedAuditTemplate.cshtml"
, Tuple.Create<string,object,bool> ("", i % 2 == 0 ? "stripe" : ""

#line default
#line hidden
, false)
);
WriteLiteral(">\n                        <td");

WriteLiteral(" colspan=\"10\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"tagsList\"");

WriteLiteral(">\n");


#line 462 "CompletedAuditTemplate.cshtml"
                                

#line default
#line hidden

#line 462 "CompletedAuditTemplate.cshtml"
                                 foreach (var tag in task.Tags)
                                {
                                    var backgroundColor = GetTagBackgroundColor(tag.ColorCode);


#line default
#line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"tagItem\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 465 "CompletedAuditTemplate.cshtml"
                                          , Tuple.Create<string,object,bool> (" ", backgroundColor

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n");


#line 466 "CompletedAuditTemplate.cshtml"
                                        

#line default
#line hidden

#line 466 "CompletedAuditTemplate.cshtml"
                                         if (!tag.IconName.IsNullOrEmpty())
                                        {


#line default
#line hidden
WriteLiteral("                                            <i");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "tagIcon", true)

#line 468 "CompletedAuditTemplate.cshtml"
                      , Tuple.Create<string,object,bool> (" ", GetIconClass(tag.IconStyle)

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 468 "CompletedAuditTemplate.cshtml"
                                                                                       Write(tag.IconName);


#line default
#line hidden
WriteLiteral("</i>\n");


#line 469 "CompletedAuditTemplate.cshtml"
                                        }


#line default
#line hidden
WriteLiteral("                                        <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");


#line 470 "CompletedAuditTemplate.cshtml"
                                                      Write(tag.Name);


#line default
#line hidden
WriteLiteral("</span>\n                                    </div>\n");


#line 472 "CompletedAuditTemplate.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </div>\n                        </td>\n                " +
"    </tr>\n");


#line 476 "CompletedAuditTemplate.cshtml"
                }


#line default
#line hidden
WriteLiteral("                </tr>\n");


#line 478 "CompletedAuditTemplate.cshtml"
                i++;
            }


#line default
#line hidden
WriteLiteral("        </tbody>\n    </table>\n    <p");

WriteLiteral(" style=\"text-align: right; font-size: 12px; padding-right: 10px;\"");

WriteLiteral(">");


#line 482 "CompletedAuditTemplate.cshtml"
                                                                    Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_TABLE_AUDIT_SCORE_TITLE"));


#line default
#line hidden
WriteLiteral(" ");


#line 482 "CompletedAuditTemplate.cshtml"
                                                                                                                                                         Write(Model.TotalScore);


#line default
#line hidden
WriteLiteral("%</p><br><br>\n\n");


#line 484 "CompletedAuditTemplate.cshtml"
    

#line default
#line hidden

#line 484 "CompletedAuditTemplate.cshtml"
      
        var actionsAndComments = Model.Tasks.Select((task, i) => new { task, i })
            .Where(x => x.task.HasCommentsOrActions && ((x.task.Actions != null && x.task.Actions.Count != 0) || (x.task.Comments != null && x.task.Comments.Count != 0)));
    

#line default
#line hidden
WriteLiteral("\n");


#line 488 "CompletedAuditTemplate.cshtml"
    

#line default
#line hidden

#line 488 "CompletedAuditTemplate.cshtml"
     if (actionsAndComments.Any())
    {


#line default
#line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"break-before\"");

WriteLiteral("></div>\n");


#line 491 "CompletedAuditTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("    ");


#line 492 "CompletedAuditTemplate.cshtml"
     foreach (var items in actionsAndComments)
    {
        var actions = items.task.Actions ??= new List<ActionsModel>();
        var comments = items.task.Comments ??= new List<Comment>(); ;


#line default
#line hidden
WriteLiteral("        <table");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>
                    </th>
                    <th");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(" style=\"font-weight: 300\"");

WriteLiteral(">");


#line 508 "CompletedAuditTemplate.cshtml"
                                                                     Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_TABLE_COMMENTS_ACTIONS_TITLE"));


#line default
#line hidden
WriteLiteral("</span>\n                    </th>\n                </tr>\n");


#line 511 "CompletedAuditTemplate.cshtml"
                

#line default
#line hidden

#line 511 "CompletedAuditTemplate.cshtml"
                 foreach (var action in actions)
                {


#line default
#line hidden
WriteLiteral("                    <tr>\n                        <th");

WriteLiteral(" colspan=\"9\"");

WriteLiteral(">\n                            <hr />\n                        </th>\n              " +
"      </tr>\n");

WriteLiteral("                    <tr>\n");


#line 519 "CompletedAuditTemplate.cshtml"
                        

#line default
#line hidden

#line 519 "CompletedAuditTemplate.cshtml"
                         if (action == actions.First())
                        {


#line default
#line hidden
WriteLiteral("                            <td");

WriteLiteral(" style=\"vertical-align: top; text-align: right;\"");

WriteLiteral("><p>");


#line 521 "CompletedAuditTemplate.cshtml"
                                                                               Write(items.i + 1);


#line default
#line hidden
WriteLiteral("</p></td>\n");


#line 522 "CompletedAuditTemplate.cshtml"
                        }
                        else
                        {


#line default
#line hidden
WriteLiteral("                            <td></td>\n");


#line 526 "CompletedAuditTemplate.cshtml"
                        }


#line default
#line hidden
WriteLiteral("                        ");


#line 527 "CompletedAuditTemplate.cshtml"
                          
                            var resources = new List<string>();

                            var assignedUsers = action.AssignedUsers.Select(a => a.Name);
                            var assignedAreas = action.AssignedAreas.Select(a => a.Name);

                            resources.AddRange(assignedUsers);
                            resources.AddRange(assignedAreas);
                        

#line default
#line hidden
WriteLiteral("\n                        <td");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral(">\n                            <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral("><strong>");


#line 537 "CompletedAuditTemplate.cshtml"
                                                        Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_COMMENT"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 537 "CompletedAuditTemplate.cshtml"
                                                                                                                                      Write(action.Comment);


#line default
#line hidden
WriteLiteral("</p>\n                            <p");

WriteLiteral(" class=\"wrap-content\"");

WriteLiteral("><strong>");


#line 538 "CompletedAuditTemplate.cshtml"
                                                        Write(TranslateExtension.GetValueFromDictionary("ACTION_SCREEN_TITLE"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 538 "CompletedAuditTemplate.cshtml"
                                                                                                                                     Write(action.Description);


#line default
#line hidden
WriteLiteral("</p>\n                            <p><strong>");


#line 539 "CompletedAuditTemplate.cshtml"
                                   Write(TranslateExtension.GetValueFromDictionary("ACTION_RESOURCES_EDITED"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 539 "CompletedAuditTemplate.cshtml"
                                                                                                                    Write(string.Join(", ", resources));


#line default
#line hidden
WriteLiteral(" </p>\n                            <p><strong>");


#line 540 "CompletedAuditTemplate.cshtml"
                                   Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_CREATED"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 540 "CompletedAuditTemplate.cshtml"
                                                                                                                  Write(Settings.ConvertDateTimeToLocal(action.CreatedAt)?.ToString(PdfConstants.GetDateTimeFormat(), null));


#line default
#line hidden
WriteLiteral(", ");


#line 540 "CompletedAuditTemplate.cshtml"
                                                                                                                                                                                                                         Write(action.CreatedBy);


#line default
#line hidden
WriteLiteral("</p>\n                            <p><strong>");


#line 541 "CompletedAuditTemplate.cshtml"
                                   Write(TranslateExtension.GetValueFromDictionary("ACTIONS_SCREEN_DUE_DATE"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 541 "CompletedAuditTemplate.cshtml"
                                                                                                                     Write(Settings.ConvertDateTimeToLocal(action.DueDate)?.ToString(PdfConstants.GetDateFormat(), null));


#line default
#line hidden
WriteLiteral("</p>\n                            <p><strong>");


#line 542 "CompletedAuditTemplate.cshtml"
                                   Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_PICTURES"));


#line default
#line hidden
WriteLiteral(":</strong></p>\n                        </td>\n                    </tr>\n");


#line 545 "CompletedAuditTemplate.cshtml"
                    if (action.Images != null && action.Images.Any())
                    {


#line default
#line hidden
WriteLiteral("                        <tr>\n                            <td");

WriteLiteral(" style=\"background: #eee\"");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral("></td>\n                            <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                                <div");

WriteLiteral(" class=\"action-pictures-box no-padding\"");

WriteLiteral(">\n");


#line 551 "CompletedAuditTemplate.cshtml"
                                    

#line default
#line hidden

#line 551 "CompletedAuditTemplate.cshtml"
                                     foreach (var image in action.Images)
                                    {


#line default
#line hidden
WriteLiteral("                                        <img");

WriteAttribute ("src", " src=\"", "\""

#line 553 "CompletedAuditTemplate.cshtml"
           , Tuple.Create<string,object,bool> ("", ImageHelpers.GetFullImageUrlFromName(image)

#line default
#line hidden
, false)
);
WriteLiteral(" style=\"height:90px; width:90px;\"");

WriteLiteral(" />\n");


#line 554 "CompletedAuditTemplate.cshtml"
                                    }


#line default
#line hidden
WriteLiteral("                                </div>\n                            </td>\n        " +
"                </tr>\n");


#line 558 "CompletedAuditTemplate.cshtml"
                    }

                    if (action.Tags != null && action.Tags.Any())
                    {


#line default
#line hidden
WriteLiteral("                        <tr>\n                            <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral("></td>\n                            <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                                <div");

WriteLiteral(" class=\"tagsList\"");

WriteLiteral(">\n");


#line 566 "CompletedAuditTemplate.cshtml"
                                    

#line default
#line hidden

#line 566 "CompletedAuditTemplate.cshtml"
                                     foreach (var tag in action.Tags)
                                    {
                                        var backgroundColor = GetTagBackgroundColor(tag.ColorCode);


#line default
#line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"tagItem\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 569 "CompletedAuditTemplate.cshtml"
                                              , Tuple.Create<string,object,bool> (" ", backgroundColor

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n");


#line 570 "CompletedAuditTemplate.cshtml"
                                            

#line default
#line hidden

#line 570 "CompletedAuditTemplate.cshtml"
                                             if (!tag.IconName.IsNullOrEmpty())
                                            {


#line default
#line hidden
WriteLiteral("                                                <i");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "tagIcon", true)

#line 572 "CompletedAuditTemplate.cshtml"
                          , Tuple.Create<string,object,bool> (" ", GetIconClass(tag.IconStyle)

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 572 "CompletedAuditTemplate.cshtml"
                                                                                           Write(tag.IconName);


#line default
#line hidden
WriteLiteral("</i>\n");


#line 573 "CompletedAuditTemplate.cshtml"
                                            }


#line default
#line hidden
WriteLiteral("                                            <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");


#line 574 "CompletedAuditTemplate.cshtml"
                                                          Write(tag.Name);


#line default
#line hidden
WriteLiteral("</span>\n                                        </div>\n");


#line 576 "CompletedAuditTemplate.cshtml"
                                    }


#line default
#line hidden
WriteLiteral("                                </div>\n                            </td>\n        " +
"                </tr>\n");


#line 580 "CompletedAuditTemplate.cshtml"
                    }
                }


#line default
#line hidden
WriteLiteral("                ");


#line 582 "CompletedAuditTemplate.cshtml"
                 foreach (var comment in comments)
                {


#line default
#line hidden
WriteLiteral("                    <tr>\n                        <th");

WriteLiteral(" colspan=\"9\"");

WriteLiteral(">\n                            <hr />\n                        </th>\n              " +
"      </tr>\n");

WriteLiteral("                    <tr>\n");


#line 590 "CompletedAuditTemplate.cshtml"
                        

#line default
#line hidden

#line 590 "CompletedAuditTemplate.cshtml"
                         if (actions.Count() == 0 && comment == comments.First())
                        {


#line default
#line hidden
WriteLiteral("                            <td");

WriteLiteral(" style=\"vertical-align: top; text-align: right;\"");

WriteLiteral("><p>");


#line 592 "CompletedAuditTemplate.cshtml"
                                                                               Write(items.i + 1);


#line default
#line hidden
WriteLiteral("</p></td>\n");


#line 593 "CompletedAuditTemplate.cshtml"
                        }
                        else
                        {


#line default
#line hidden
WriteLiteral("                            <td></td>\n");


#line 597 "CompletedAuditTemplate.cshtml"
                        }


#line default
#line hidden
WriteLiteral("                        <td");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral(">\n                            <p><strong>");


#line 599 "CompletedAuditTemplate.cshtml"
                                   Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_COMMENT"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 599 "CompletedAuditTemplate.cshtml"
                                                                                                                 Write(comment.CommentText);


#line default
#line hidden
WriteLiteral("</p>\n                            <p><strong>");


#line 600 "CompletedAuditTemplate.cshtml"
                                   Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_CREATED"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 600 "CompletedAuditTemplate.cshtml"
                                                                                                                  Write(Settings.ConvertDateTimeToLocal(comment.CommentDate)?.ToString(PdfConstants.GetDateTimeFormat(), null));


#line default
#line hidden
WriteLiteral(", ");


#line 600 "CompletedAuditTemplate.cshtml"
                                                                                                                                                                                                                            Write(comment.CreatedBy);


#line default
#line hidden
WriteLiteral("</p>\n                            <p><strong>");


#line 601 "CompletedAuditTemplate.cshtml"
                                   Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_PICTURES"));


#line default
#line hidden
WriteLiteral(":</strong></p>\n                        </td>\n                    </tr>\n");


#line 604 "CompletedAuditTemplate.cshtml"
                    if (comment.Attachments != null && comment.Attachments.Any())
                    {


#line default
#line hidden
WriteLiteral("                        <tr>\n                            <td");

WriteLiteral(" style=\"background: #eee\"");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral("></td>\n                            <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                                <div");

WriteLiteral(" class=\"action-pictures-box no-padding\"");

WriteLiteral(">\n");


#line 610 "CompletedAuditTemplate.cshtml"
                                    

#line default
#line hidden

#line 610 "CompletedAuditTemplate.cshtml"
                                     foreach (var image in comment.Attachments)
                                    {


#line default
#line hidden
WriteLiteral("                                        <img");

WriteAttribute ("src", " src=\"", "\""

#line 612 "CompletedAuditTemplate.cshtml"
           , Tuple.Create<string,object,bool> ("", ImageHelpers.GetFullImageUrlFromName(image)

#line default
#line hidden
, false)
);
WriteLiteral(" style=\"height:90px; width:90px;\"");

WriteLiteral(" />\n");


#line 613 "CompletedAuditTemplate.cshtml"
                                    }


#line default
#line hidden
WriteLiteral("                                </div>\n                            </td>\n        " +
"                </tr>\n");


#line 617 "CompletedAuditTemplate.cshtml"
                    }

                    if (comment.Tags != null && comment.Tags.Any())
                    {


#line default
#line hidden
WriteLiteral("                        <tr>\n                            <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral("></td>\n                            <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                                <div");

WriteLiteral(" class=\"tagsList\"");

WriteLiteral(">\n");


#line 625 "CompletedAuditTemplate.cshtml"
                                    

#line default
#line hidden

#line 625 "CompletedAuditTemplate.cshtml"
                                     foreach (var tag in comment.Tags)
                                    {
                                        var backgroundColor = GetTagBackgroundColor(tag.ColorCode);


#line default
#line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"tagItem\"");

WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 628 "CompletedAuditTemplate.cshtml"
                                              , Tuple.Create<string,object,bool> (" ", backgroundColor

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(">\n");


#line 629 "CompletedAuditTemplate.cshtml"
                                            

#line default
#line hidden

#line 629 "CompletedAuditTemplate.cshtml"
                                             if (!tag.IconName.IsNullOrEmpty())
                                            {


#line default
#line hidden
WriteLiteral("                                                <i");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "tagIcon", true)

#line 631 "CompletedAuditTemplate.cshtml"
                          , Tuple.Create<string,object,bool> (" ", GetIconClass(tag.IconStyle)

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 631 "CompletedAuditTemplate.cshtml"
                                                                                           Write(tag.IconName);


#line default
#line hidden
WriteLiteral("</i>\n");


#line 632 "CompletedAuditTemplate.cshtml"
                                            }


#line default
#line hidden
WriteLiteral("                                            <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");


#line 633 "CompletedAuditTemplate.cshtml"
                                                          Write(tag.Name);


#line default
#line hidden
WriteLiteral("</span>\n                                        </div>\n");


#line 635 "CompletedAuditTemplate.cshtml"
                                    }


#line default
#line hidden
WriteLiteral("                                </div>\n                            </td>\n        " +
"                </tr>\n");


#line 639 "CompletedAuditTemplate.cshtml"
                    }
                }


#line default
#line hidden
WriteLiteral("                <tr");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                    <td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                        <hr");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(" />\n                    </td>\n                </tr>\n            </tbody>\n        " +
"</table>\n");


#line 648 "CompletedAuditTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("\n\n");


#line 651 "CompletedAuditTemplate.cshtml"
    

#line default
#line hidden

#line 651 "CompletedAuditTemplate.cshtml"
      
        var pictureProofTasks = Model.Tasks.Select((task, i) => new { task, i })
            .Where(x => x.task.HasPictureProof && x.task.PictureProofMediaItems.Count > 0);
    

#line default
#line hidden
WriteLiteral("\n");


#line 655 "CompletedAuditTemplate.cshtml"
    

#line default
#line hidden

#line 655 "CompletedAuditTemplate.cshtml"
     if (pictureProofTasks.Any())
    {


#line default
#line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"break-before\"");

WriteLiteral("></div>\n");


#line 658 "CompletedAuditTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("    ");


#line 659 "CompletedAuditTemplate.cshtml"
     foreach (var items in pictureProofTasks)
    {
        var pictureProof = items.task.PictureProofMediaItems ??= new List<MediaItem>();


#line default
#line hidden
WriteLiteral("        <table");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>
                    </th>
                    <th");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(" style=\"font-weight: 300\"");

WriteLiteral(">");


#line 674 "CompletedAuditTemplate.cshtml"
                                                                     Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_TABLE_PICTURE_PROOF_TITLE"));


#line default
#line hidden
WriteLiteral("</span>\n                    </th>\n                </tr>\n                <tr>\n    " +
"                <th");

WriteLiteral(" colspan=\"9\"");

WriteLiteral(">\n                        <hr />\n                    </th>\n                </tr>\n" +
"                <tr>\n                    <td");

WriteLiteral(" style=\"vertical-align: top; text-align: right;\"");

WriteLiteral("><p>");


#line 683 "CompletedAuditTemplate.cshtml"
                                                                       Write(items.i + 1);


#line default
#line hidden
WriteLiteral("</p></td>\n                    <td");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral(">\n                        <p><strong>");


#line 685 "CompletedAuditTemplate.cshtml"
                               Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_CREATED"));


#line default
#line hidden
WriteLiteral(":</strong> ");


#line 685 "CompletedAuditTemplate.cshtml"
                                                                                                             Write(pictureProof.First().CreatedAt.ToString(PdfConstants.GetDateTimeFormat(), null));


#line default
#line hidden
WriteLiteral("</p>\n                        <p><strong>");


#line 686 "CompletedAuditTemplate.cshtml"
                               Write(TranslateExtension.GetValueFromDictionary("GENERATE_PDF_PICTURES"));


#line default
#line hidden
WriteLiteral(":</strong></p>\n                    </td>\n                </tr>\n");


#line 689 "CompletedAuditTemplate.cshtml"
                

#line default
#line hidden

#line 689 "CompletedAuditTemplate.cshtml"
                 if (pictureProof.Count() > 0)
                {


#line default
#line hidden
WriteLiteral("                    <tr>\n                        <td");

WriteLiteral(" style=\"background: #eee\"");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral("></td>\n                        <td");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"action-pictures-box no-padding\"");

WriteLiteral(">\n");


#line 695 "CompletedAuditTemplate.cshtml"
                                

#line default
#line hidden

#line 695 "CompletedAuditTemplate.cshtml"
                                 foreach (var image in pictureProof)
                                {


#line default
#line hidden
WriteLiteral("                                    <img");

WriteAttribute ("src", " src=\"", "\""

#line 697 "CompletedAuditTemplate.cshtml"
       , Tuple.Create<string,object,bool> ("", ImageHelpers.GetFullImageUrlFromName(image.PictureUrl)

#line default
#line hidden
, false)
);
WriteLiteral(" style=\"height:90px; width:90px;\"");

WriteLiteral(" />\n");


#line 698 "CompletedAuditTemplate.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </div>\n                        </td>\n                " +
"    </tr>\n");


#line 702 "CompletedAuditTemplate.cshtml"
                }


#line default
#line hidden
WriteLiteral("                <tr");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                    <td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(">\n                        <hr");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(" />\n                    </td>\n                </tr>\n            </tbody>\n        " +
"</table>\n");


#line 710 "CompletedAuditTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("\n\n\n\n\n    <table");

WriteLiteral(" style=\"width: 100%; padding:20px; page-break-inside: avoid\"");

WriteLiteral(">\n        <tbody>\n            <tr>\n                <td>&nbsp;</td>\n");


#line 720 "CompletedAuditTemplate.cshtml"
                

#line default
#line hidden

#line 720 "CompletedAuditTemplate.cshtml"
                 foreach (var signature in (Model.Signatures ?? new List<SignatureModel>()))
                {


#line default
#line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\n");

WriteLiteral("                        ");


#line 723 "CompletedAuditTemplate.cshtml"
                   Write(signature.SignedBy);


#line default
#line hidden
WriteLiteral("\n                    </td>\n");


#line 725 "CompletedAuditTemplate.cshtml"
                }


#line default
#line hidden
WriteLiteral("\n            </tr>\n            <tr>\n                <td><span");

WriteLiteral(" style=\"color:#A9A9A9;\"");

WriteLiteral(">EZ-GO Audit Report</span></td>\n");


#line 730 "CompletedAuditTemplate.cshtml"
                

#line default
#line hidden

#line 730 "CompletedAuditTemplate.cshtml"
                 foreach (var signature in (Model.Signatures ?? new List<SignatureModel>()))
                {
                    // Audits that don't require signature still have a signature object, just without an image
                    if (!string.IsNullOrEmpty(signature.SignatureImage))
                    {
                        var signatureUrl = @ImageHelpers.GetFullImageUrlFromName(signature.SignatureImage);

                        

#line default
#line hidden
WriteLiteral("<td><img");

WriteLiteral(" alt=\"afbeelding\"");

WriteAttribute ("src", " src=\"", "\""

#line 737 "CompletedAuditTemplate.cshtml"
                , Tuple.Create<string,object,bool> ("", signatureUrl

#line default
#line hidden
, false)
);
WriteLiteral(" height=\"100\"");

WriteLiteral(" style=\"display:block; margin: auto\"");

WriteLiteral(" /></td>\n");


#line 738 "CompletedAuditTemplate.cshtml"
                    }
                }


#line default
#line hidden
WriteLiteral("            </tr>\n        </tbody>\n    </table>\n\n</body>\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class CompletedAuditTemplateBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
